# # print("Welcome to the tip calculator!")
# # bill = float(input("What was the total bill? $"))
# # tip = int(input("What percentage tip would you like to give? 10 12 15 "))
# # people = int(input("How many people to split the bill? "))
# print("Welcome to the tip calculator")
# total_bill= float(input("what was the total bill?\n"))
# tip=float(input("How much tip you would like to give?\n"))
# number=float(input("How many prople to split the bill?\n"))
# tip_to_pay=((total_bill*(tip/100)+total_bill) / number)
# # print(f"each person should pay:{tip_to_pay}")

print("Welcome to the tip calculator!")
bill=float(input("What was the total bill?\n"))
tip= int(input ("How much tip would you like to give? 10, 12 or 15?\n"))
number_of_people= int(input("How many people to split the bill?"))
pay= (bill+(bill*tip/100))/number_of_people
print(f"Each person should pay: {pay}")